import { useEffect, useState } from 'react';

interface EditorViewProps {
  projectId: string;
  filePath: string | null;
}

export default function EditorView({ projectId, filePath }: EditorViewProps) {
  const [content, setContent] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!filePath) {
      setContent('');
      setError(null);
      return;
    }

    let mounted = true;
    const fetchFileContent = async () => {
      setLoading(true);
      setError(null);
      try {
        const response = await fetch(`http://localhost:8000/projects/${projectId}/files/${filePath}`);
        if (response.ok && mounted) {
          const data = await response.json();
          setContent(data.content);
        } else if (mounted) {
          setError(`Failed to load file: ${response.statusText}`);
        }
      } catch (err) {
        if (mounted) setError(`Error fetching file: ${err}`);
      } finally {
        if (mounted) setLoading(false);
      }
    };

    fetchFileContent();
  }, [projectId, filePath]);

  if (!filePath) {
    return (
      <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#666', backgroundColor: '#1e1e1e' }}>
        <p>Select a file to view its contents</p>
      </div>
    );
  }

  const isJson = filePath.endsWith('.json');
  
  // Basic JSON Syntax Highlighter
  const formatJson = (jsonString: string) => {
    if (!isJson) return jsonString;
    try {
      const obj = JSON.parse(jsonString);
      const pretty = JSON.stringify(obj, null, 2);
      return pretty.replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g, function (match) {
        let color = '#d4d4d4'; // default
        if (/^"/.test(match)) {
          if (/:$/.test(match)) color = '#9cdcfe'; // key
          else color = '#ce9178'; // string
        } else if (/true|false/.test(match)) {
          color = '#569cd6'; // boolean
        } else if (/null/.test(match)) {
          color = '#569cd6'; // null
        } else {
          color = '#b5cea8'; // number
        }
        return `<span style="color: ${color}">${match}</span>`;
      });
    } catch {
      return jsonString; // If parsing fails, return raw
    }
  };

  const getMetadata = () => {
    let agent = 'Unknown';
    if (filePath.startsWith('planning/')) agent = 'Planning Agent';
    else if (filePath.startsWith('src/')) agent = 'Coding Agent';
    return { agent, timestamp: new Date().toLocaleTimeString() };
  };

  const metadata = getMetadata();

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', backgroundColor: '#1e1e1e', overflow: 'hidden' }}>
      <div style={{ 
        backgroundColor: '#2d2d2d', 
        padding: '8px 15px', 
        color: '#d4d4d4',
        fontSize: '13px',
        borderBottom: '1px solid #111',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center'
      }}>
        <div><span style={{ marginRight: 8 }}>📄</span> {filePath}</div>
        <div style={{ fontSize: '11px', color: '#888' }}>
          Generated by: <span style={{ color: '#007acc' }}>{metadata.agent}</span> | Read Only
        </div>
      </div>
      
      <div style={{ flex: 1, overflow: 'auto', padding: '15px' }}>
        {loading ? (
          <div style={{ color: '#888' }}>Loading...</div>
        ) : error ? (
          <div style={{ color: '#f48771' }}>{error}</div>
        ) : (
          <pre 
            style={{ 
              margin: 0, 
              color: isJson ? '#ce9178' : '#9cdcfe', 
              fontFamily: 'Consolas, "Courier New", monospace',
              fontSize: '14px',
              whiteSpace: 'pre-wrap'
            }}
            dangerouslySetInnerHTML={{ __html: formatJson(content) }}
          />
        )}
      </div>
    </div>
  );
}
